name: Cart CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci_cd_common:
    runs-on: self-hosted
    steps:
    - uses: raghudevopsb87/reusable-github-actions/.github/workflows/ci.yml@main
      with:
        component: cart
        apptype: nodejs

